---
name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-plugin-up
          pipx inject poetry poetry-dynamic-versioning

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install dependencies
        run: poetry install --without=dev --verbose

      - name: Build
        run: poetry build --verbose

      - name: Publish
        run: poetry publish --username=__token__ --password "${PYPI_API_TOKEN}" --verbose
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

      - name: Update release assets
        uses: softprops/action-gh-release@v1
        with:
          # generate_release_notes: true
          files: |
            dist/*
